version: '3.8'

services:
  consolidata-api:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    volumes:
      - ../../database:/app/database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  consolidata-frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ../../frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - consolidata-api
    restart: unless-stopped

volumes:
  database_data: 