services:
  - type: web
    name: consolidata-washroom-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT wsgi:app
    healthCheckPath: /api/health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.9.18
    
  - type: static
    name: consolidata-washroom-frontend
    staticPublishPath: ./frontend
    buildCommand: echo "Static files ready"
    routes:
      - type: rewrite
        source: /api/*
        destination: https://consolidata-washroom-api.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff 